import type { Dispenser, Transaction, Vehicle, Operation, Shift } from "./types"

export const mockDispensers: Dispenser[] = [
  {
    id: "1",
    stationId: "station-1",
    number: 1,
    status: "idle",
    currentPrice: 5200,
    temperature: 22,
    pressure: 200,
    lastHeartbeat: new Date(),
  },
  {
    id: "2",
    stationId: "station-1",
    number: 2,
    status: "filling",
    currentPrice: 5200,
    temperature: 23,
    pressure: 198,
    lastHeartbeat: new Date(),
  },
  {
    id: "3",
    stationId: "station-1",
    number: 3,
    status: "idle",
    currentPrice: 5200,
    temperature: 21,
    pressure: 202,
    lastHeartbeat: new Date(),
  },
  {
    id: "4",
    stationId: "station-1",
    number: 4,
    status: "disconnected",
    currentPrice: 5200,
    lastHeartbeat: new Date(Date.now() - 300000),
  },
  {
    id: "5",
    stationId: "station-1",
    number: 5,
    status: "idle",
    currentPrice: 5200,
    temperature: 22,
    pressure: 199,
    lastHeartbeat: new Date(),
  },
  {
    id: "6",
    stationId: "station-1",
    number: 6,
    status: "idle",
    currentPrice: 5200,
    temperature: 24,
    pressure: 201,
    lastHeartbeat: new Date(),
  },
]

export const mockTransactions: Transaction[] = [
  {
    id: "tx-1",
    dispenserId: "2",
    plate: "01A123BC",
    startTime: new Date(Date.now() - 180000),
    volumeM3: 12.5,
    priceAtStart: 5200,
    amountSum: 65000,
    status: "filling",
    operatorId: "op-1",
  },
  {
    id: "tx-2",
    dispenserId: "1",
    plate: "10B456DE",
    startTime: new Date(Date.now() - 600000),
    endTime: new Date(Date.now() - 300000),
    volumeM3: 25.3,
    priceAtStart: 5200,
    amountSum: 131560,
    status: "finished",
    operatorId: "op-1",
  },
  {
    id: "tx-3",
    dispenserId: "3",
    plate: "30C789FG",
    startTime: new Date(Date.now() - 900000),
    endTime: new Date(Date.now() - 600000),
    volumeM3: 18.7,
    priceAtStart: 5200,
    amountSum: 97240,
    status: "paid",
    operatorId: "op-1",
  },
  {
    id: "tx-4",
    dispenserId: "3",
    plate: "20D111HH",
    startTime: new Date(Date.now() - 1200000),
    endTime: new Date(Date.now() - 900000),
    volumeM3: 15.2,
    priceAtStart: 5200,
    amountSum: 79040,
    status: "finished" as const,
    operatorId: "op-1",
  },
  {
    id: "tx-5",
    dispenserId: "5",
    plate: "50E222JJ",
    startTime: new Date(Date.now() - 1800000),
    endTime: new Date(Date.now() - 1500000),
    volumeM3: 22.8,
    priceAtStart: 5200,
    amountSum: 118560,
    status: "paid" as const,
    operatorId: "op-1",
  },
  {
    id: "tx-6",
    dispenserId: "6",
    plate: "60F333KK",
    startTime: new Date(Date.now() - 2400000),
    endTime: new Date(Date.now() - 2100000),
    volumeM3: 19.5,
    priceAtStart: 5200,
    amountSum: 101400,
    status: "canceled" as const,
    operatorId: "op-1",
  },
]

export const mockVehicles: Vehicle[] = [
  {
    id: "v-1",
    plate: "01A123BC",
    make: "Chevrolet",
    model: "Lacetti",
    year: 2018,
    color: "Oq",
    fuelType: "CNG",
    passportStatus: "valid",
    techInspectionStatus: "valid",
    lastCheckAt: new Date(Date.now() - 86400000),
  },
  {
    id: "v-2",
    plate: "10B456DE",
    make: "Daewoo",
    model: "Nexia",
    year: 2015,
    color: "Qora",
    fuelType: "CNG",
    passportStatus: "valid",
    techInspectionStatus: "expired",
    lastCheckAt: new Date(Date.now() - 86400000 * 30),
  },
  {
    id: "v-3",
    plate: "30C789FG",
    make: "Chevrolet",
    model: "Spark",
    year: 2020,
    color: "Qizil",
    fuelType: "CNG",
    passportStatus: "valid",
    techInspectionStatus: "valid",
    lastCheckAt: new Date(Date.now() - 86400000 * 5),
  },
  {
    id: "v-4",
    plate: "20D111HH",
    make: "Chevrolet",
    model: "Cobalt",
    year: 2019,
    color: "Kulrang",
    fuelType: "CNG",
    passportStatus: "expired" as const,
    techInspectionStatus: "valid" as const,
    lastCheckAt: new Date(Date.now() - 86400000 * 400),
  },
  {
    id: "v-5",
    plate: "50E222JJ",
    make: "Daewoo",
    model: "Matiz",
    year: 2016,
    color: "Ko'k",
    fuelType: "CNG",
    passportStatus: "valid" as const,
    techInspectionStatus: "expired" as const,
    lastCheckAt: new Date(Date.now() - 86400000 * 200),
  },
  {
    id: "v-6",
    plate: "60F333KK",
    make: "Chevrolet",
    model: "Nexia",
    year: 2017,
    color: "Oq",
    fuelType: "CNG",
    passportStatus: "valid" as const,
    techInspectionStatus: "valid" as const,
    lastCheckAt: new Date(Date.now() - 86400000 * 10),
  },
]

export const mockOperations: Operation[] = [
  {
    transaction: mockTransactions[0],
    vehicle: mockVehicles[0],
    dispenser: mockDispensers[1],
  },
  {
    transaction: mockTransactions[1],
    vehicle: mockVehicles[1],
    dispenser: mockDispensers[0],
  },
  {
    transaction: mockTransactions[2],
    vehicle: mockVehicles[2],
    dispenser: mockDispensers[2],
  },
  {
    transaction: mockTransactions[3],
    vehicle: mockVehicles[3],
    dispenser: mockDispensers[2],
  },
  {
    transaction: mockTransactions[4],
    vehicle: mockVehicles[4],
    dispenser: mockDispensers[4],
  },
  {
    transaction: mockTransactions[5],
    vehicle: mockVehicles[5],
    dispenser: mockDispensers[5],
  },
]

export const mockShifts: Shift[] = [
  {
    id: "shift-1",
    operatorId: "op-1",
    stationId: "station-1",
    openedAt: new Date(Date.now() - 28800000), // 8 hours ago
    openingBalanceCash: 500000,
    openingBalanceCard: 0,
  },
  {
    id: "shift-2",
    operatorId: "op-1",
    stationId: "station-1",
    openedAt: new Date(Date.now() - 115200000), // 32 hours ago
    closedAt: new Date(Date.now() - 86400000), // 24 hours ago
    openingBalanceCash: 300000,
    openingBalanceCard: 0,
    cashTotal: 450000,
    cardTotal: 250000,
    difference: 0,
    notes: "Smena muvaffaqiyatli yakunlandi",
  },
  {
    id: "shift-3",
    operatorId: "op-2",
    stationId: "station-1",
    openedAt: new Date(Date.now() - 201600000), // 56 hours ago
    closedAt: new Date(Date.now() - 172800000), // 48 hours ago
    openingBalanceCash: 250000,
    openingBalanceCard: 0,
    cashTotal: 380000,
    cardTotal: 320000,
    difference: -10000,
    notes: "Kichik tafovut aniqlandi",
  },
]
